name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Determine HTTP Method
      run: |
        URL="${{ secrets.API_ENDPOINT }}/object/identifier" # Adjust endpoint
        RESPONSE_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" -X GET "$URL")
        if [ "$RESPONSE_CODE" -eq 404 ]; then
          echo "METHOD=POST" >> $GITHUB_ENV
        else
          echo "METHOD=PUT" >> $GITHUB_ENV

    - name: Post Origin JSON Data
      run: |
        curl -X $METHOD -H "Content-Type: application/json" -d @origin.json ${{ secrets.ORIGIN_API_ENDPOINT }}
      env:
        API_KEY: ${{ secrets.API_TOKEN }}

    - name: Post WAF JSON Data
      run: |
        curl -X $METHOD -H "Content-Type: application/json" -d @waf.json ${{ secrets.WAF_API_ENDPOINT }}
      env:
        API_KEY: ${{ secrets.API_TOKEN }}

    - name: Post 2nd WAF JSON Data
      run: |
        curl -X $METHOD -H "Content-Type: application/json" -d @drupal-waf.json ${{ secrets.WAF_API_ENDPOINT }}
      env:
        API_KEY: ${{ secrets.API_TOKEN }}

    - name: Post Load Balancer JSON Data
      run: |
        curl -X $METHOD -H "Content-Type: application/json" -d @loadbalancer.json ${{ secrets.LB_API_ENDPOINT }}
      env:
        API_KEY: ${{ secrets.API_TOKEN }}
